const CHARACTER_KEYS = {
    ALIGNMENT: "alignment",
    ARMOR: "armor",
    BACKGROUND: "background",
    CLASS: "class",
    DEATH_SAVES: "deathSaves",
    EQUIPMENT: "equipment",
    FEATURES: "featuresTraits",
    GOLD: "gold",
    HP: "hp",
    INITIATIVE: "initiative",
    INSPIRATION: "inspiration",
    LANGUAGES: "languages",
    LEVEL: "level",
    NAME: "name",
    PASSIVE_PERCEPTION: "passivePerception",
    PROFICIENCIES: "proficiencies",
    PROFICIENCY_BONUS: "proficiencyBonus",
    RACE: "race",
    SAVING_THROWS: "savingThrows",
    SKILLS: "skills",
    SPEED: "speed",
    SPELL_BONUS: "spellBonus",
    SPELL_CAST_STAT: "spellCastStat",
    SPELL_SAVE_DC: "spellSaveDc",
    SPELLS: "spells",
    SPELL_SLOTS: "spellSlots",
    STATS: "stats",
    TIME_CREATED: "timeCreated",
    TREASURES: "treasures",
    WEAPONS: "weapons",
}

const CHARACTER_NAMES = {
    [CHARACTER_KEYS.ALIGNMENT]: "Alignment",
    [CHARACTER_KEYS.ARMOR]: "Armor",
    [CHARACTER_KEYS.BACKGROUND]: "Background",
    [CHARACTER_KEYS.CLASS]: "Class",
    [CHARACTER_KEYS.DEATH_SAVES]: "Death Saves",
    [CHARACTER_KEYS.EQUIPMENT]: "Equipment",
    [CHARACTER_KEYS.FEATURES]: "Features & Traits",
    [CHARACTER_KEYS.GOLD]: "Gold",
    [CHARACTER_KEYS.HP]: "Hp",
    [CHARACTER_KEYS.INITIATIVE]: "Initiative",
    [CHARACTER_KEYS.LANGUAGES]: "Languages",
    [CHARACTER_KEYS.LEVEL]: "Level",
    [CHARACTER_KEYS.NAME]: "Name",
    [CHARACTER_KEYS.PASSIVE_PERCEPTION]: "Passive Perception",
    [CHARACTER_KEYS.PROFICIENCIES]: "Proficiencies",
    [CHARACTER_KEYS.PROFICIENCY_BONUS]: "Proficiency Bonus",
    [CHARACTER_KEYS.RACE]: "Race",
    [CHARACTER_KEYS.SAVING_THROWS]: "Saving Throws",
    [CHARACTER_KEYS.SKILLS]: "Skills",
    [CHARACTER_KEYS.SPEED]: "Speed",
    [CHARACTER_KEYS.SPELL_BONUS]: "Spell Bonus",
    [CHARACTER_KEYS.SPELL_CAST_STAT]: "Spell Cast Stat",
    [CHARACTER_KEYS.SPELL_SAVE_DC]: "Spell Save Dc",
    [CHARACTER_KEYS.SPELLS]: "Spells",
    [CHARACTER_KEYS.STATS]: "Stats",
    [CHARACTER_KEYS.TREASURES]: "Treasures",
    [CHARACTER_KEYS.TREASURES]: "Time Registered",
    [CHARACTER_KEYS.WEAPONS]: "Weapons",
}

export { CHARACTER_KEYS, CHARACTER_NAMES }